name: Sync to HuggingFace Space

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git remote add hf https://HamzaHF1:$HF_TOKEN@huggingface.co/spaces/HamzaHF1/ATLAS-Bot
          git push hf main --force
